# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: kish
    main: ./cmd/kish/
    binary: kish
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
  - id: kish-server
    main: ./cmd/kish-server/
    binary: kish-server
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
archives:
  - id: kish
    builds:
      - kish
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
  - id: kish-server
    builds:
      - kish-server
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

brews:
  - name: kish
    repository:
      owner: no2a
      name: homebrew-tap
    folder: Formula
    url_template: "https://github.com/no2a/kish/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: no2a
      email: arata776@gmail.com
    description: "kish client"
    ids: [kish]
